-   repo: git@github.com:pre-commit/pre-commit-hooks.git
    sha: 3fa02652357ff0dbb42b5bc78c673b7bc105fcf3
    hooks:
    -   id: check-json
    -   id: pretty-format-json
    -   id: check-symlinks
    -   id: check-yaml
    -   id: trailing-whitespace
-   repo: git@github.com:pre-commit/mirrors-eslint
    sha: e62419a27e36d6a9ba9a6bc48c53b23beab0cdd8
    hooks:
    -   id: eslint
        args:
            - --config .eslintrc
            - --ext .js,.jsx
            - src tests assets/js
