# reddit-mobile Dockerfile for deploying on staging/prod

FROM node:5.12

ENV DEBIAN_FRONTEND noninteractive

ENV MINIFY_ASSETS "false"

# You'll want to override these at runtime
ENV GOOGLE_ANALYTICS_ID UA-XXXXXX-1
ENV OAUTH_CLIENT_ID XXXXXXXXX
ENV SECRET_OAUTH_CLIENT_ID XXXXXXXXX
ENV OAUTH_SECRET XXXXXXXXX

ADD package.json /src/package.json
WORKDIR /src
ADD . /src/

EXPOSE 8888
# start the server
CMD npm install && npm run dev-build && npm run dev-server
